### ISSUE TITLE
Notes component not dispatching initNotesRef()  on mount() ie. Notes lists not displaying

### ISSUE THREAD

**Issue by pi-ron** [vue-bulma/vuexfire-admin#4]
User's notes & completed notes are currently not displaying. Push to database working OK.

**Comment by dkmin** [comment]
Same here. Thanks

**Comment by pi-ron** [comment]
Action is never binding ref to store

`/client/store/modules/notes/index.js`
``````
  setNotesRef: firebaseAction(({ bindFirebaseRef, rootState }, ref) => {
    bindFirebaseRef(refTypes.NOTES, ref)
  }),
``````

**Comment by pi-ron** [comment]
This may be due to lack of firebase-admin service worker and lack of user data it adds, will look into this.

**Comment by pi-ron** [comment]
For some reason, vuex action `initNotesRef`is not triggering when the `<Notes>` component mounts.  Dispatching this action via console correctly loads the notes.  I've moved the action dispatcher out to the parent component `mounted()` method.

@dkmin Could you please have a try of this with the latest code, and see if notes are loading for you?

**Comment by dkmin** [comment]
I share the following results.
I hope it would be helped
<img width="1243" alt="screen shot 2017-08-11 at 5 21 44 pm" src="https://user-images.githubusercontent.com/981925/29205756-b00d8cbc-7eb9-11e7-9afa-88028a6fe0c3.png">

**Comment by pi-ron** [comment]
@dkmin Thank you, can you please confirm if the New Note form is pushing data to your database at `/notes/$UID/$NoteID/...` ?

**Comment by pi-ron** [comment]
This was caused by default firebase rules.  

@dkmin I've added some example rules to the README.md if you would like to try them out.
